### PR TITLE
Add Contributors

### PR DESCRIPTION
**Pull request by CodingSpecies**

### CODE REVIEW

**Comment by CodingSpecies** [comment]
@all-contributors please add @CodingSpecies for project management.

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for content, projectManagement, review, code

**Comment by CodingSpecies** [comment]
@all-contributors please add @AvidCoder101 for documentation

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for documentation, code, review, projectManagement

**Comment by AvidCoder101** [comment]
@all-contributors please add @CodingSpecies for documentation, code, review, projectManagement

**Comment by CodingSpecies** [comment]
@all-contributors please add @AvidCoder101  for content

**Comment by CodingSpecies** [comment]
@all-contributors please add @CodingSpecies for project management

**Comment by CodingSpecies** [comment]
@all-contributors please add @AvidCoder101  for content

**Comment by CodingSpecies** [comment]
@all-contributors please add @CodingSpecies  for project management

**Comment by CodingSpecies** [comment]
@all-contributors please add @thuongtruong1009  for content

**Pull request merged**
